MVC/Models/Employee.cs
namespace UserAccount.Models
{
    public class Employee
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public double Phone { get; set; }
    }
}

MVC/Models/ResponseObj.cs
namespace UserAccount.Models
{
    public class ResponseObj
    {
        public string jwt { get; set; }
    }
}

MVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using UserAccount.Models;

namespace UserAccount.Controllers
{
    public class LoginController : Controller
    {
        string BASE_URL = Environment.GetEnvironmentVariable("BACKEND_STRING_AUTH");

        public ActionResult Index()
        {
            return View();

        }

        public async Task<ActionResult> Authenticate(Employee employeeData)
        {
            using (var client = new HttpClient())
            {
                var uri = new Uri(BASE_URL + "/api2/login");

                StringContent jsonContent = new(System.Text.Json.JsonSerializer.Serialize(employeeData), Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync(uri, jsonContent);


                if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
                {
                    return RedirectToAction("Index", "Login");

                }
                ResponseObj token = await response.Content.ReadAsAsync<ResponseObj>(new[] { new JsonMediaTypeFormatter() });

                HttpContext.Session.SetString("Token", token.jwt);


               var handler = new JwtSecurityTokenHandler();
                var tokenObj = handler.ReadJwtToken(token.jwt);

                var payLoad = tokenObj.Payload.FirstOrDefault().Value;

                return RedirectToAction("Index", "UserData", new { id = payLoad });

            }

        }

    }
}

MVC/Controllers/NewAccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using UserAccount.Models;

namespace UserAccount.Controllers
{
    public class NewAccountController : Controller
    {
        string BASE_URL = Environment.GetEnvironmentVariable("BACKEND_STRING_CRUD");


        // GET: UserData
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cancel()
        {
            return RedirectToAction("Index", "Login");
        }
        // POST: HomeControlhhler1/Create
        [HttpPost]
        public async Task<ActionResult> Create(Employee employeeData)
        {
            using (var client = new HttpClient())
            {
                var uri = new Uri(BASE_URL + "api1/emp");

                StringContent jsonContent = new(JsonSerializer.Serialize(employeeData),Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync(uri,jsonContent);

            }

            return RedirectToAction("Index", "Login");

        }


    }
}

MVC/Controllers/UserDataController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;
using UserAccount.Models;

namespace UserAccount.Controllers
{
    public class UserDataController : Controller
    {
        string BASE_URL = Environment.GetEnvironmentVariable("BACKEND_STRING_CRUD");

        // GET: UserData
        public async Task<ActionResult> Index(string id)
        {
            var jwtToken = HttpContext.Session.GetString("Token");

            if (jwtToken == null)
            {
                return RedirectToAction("Index", "Login");

            }

            var handler = new JwtSecurityTokenHandler();
            var tokenObj = handler.ReadJwtToken(jwtToken);

            if (tokenObj == null)
            {
                return RedirectToAction("Index", "Login");

            }
            var payloadID = tokenObj.Payload.FirstOrDefault().Value.ToString();

            if (payloadID == null && payloadID == "")
            {
                return RedirectToAction("Index", "Login");

            }

            using (var client = new HttpClient())
            {
                var uri = new Uri(BASE_URL + "api1/emp/" + payloadID);
                
                HttpResponseMessage response = await client.GetAsync(uri);

                if(response.StatusCode == System.Net.HttpStatusCode.NoContent)
                {
                    return RedirectToAction("Index", "Login");

                }
                Employee emp =  await response.Content.ReadAsAsync<Employee>(new[] { new JsonMediaTypeFormatter() });
                return View(emp);
            }

        }

        public async Task<ActionResult> Update(Employee employeeData)
        {
            var jwtToken = HttpContext.Session.GetString("Token");

            if (jwtToken == null)
            {
                return RedirectToAction("Index", "Login");

            }

            var handler = new JwtSecurityTokenHandler();
            var tokenObj = handler.ReadJwtToken(jwtToken);

            if(tokenObj == null)
            {
                return RedirectToAction("Index", "Login");

            }
            var payloadID = tokenObj.Payload.FirstOrDefault().Value.ToString();

            if(payloadID == null && payloadID == "")
            {
                return RedirectToAction("Index", "Login");

            }
            using (var client = new HttpClient())
            {

                var uri = new Uri(BASE_URL + "api1/emp/" + payloadID);

                StringContent jsonContent = new(JsonSerializer.Serialize(employeeData), Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync(uri, jsonContent);

                return RedirectToAction("Index", new { id = employeeData.Id } );

            }


        }

        public async Task<ActionResult> Delete(string id )
        {
            var jwtToken = HttpContext.Session.GetString("Token");

            if (jwtToken == null)
            {
                return RedirectToAction("Index", "Login");

            }

            var handler = new JwtSecurityTokenHandler();
            var tokenObj = handler.ReadJwtToken(jwtToken);

            if (tokenObj == null)
            {
                return RedirectToAction("Index", "Login");

            }
            var payloadID = tokenObj.Payload.FirstOrDefault().Value.ToString();

            if (payloadID == null && payloadID == "")
            {
                return RedirectToAction("Index", "Login");

            }
            using (var client = new HttpClient())
            {

                var uri = new Uri(BASE_URL + "api1/emp/" + payloadID);

                HttpResponseMessage response = await client.DeleteAsync(uri);

                return RedirectToAction("Index", "Login");

            }

        }


    }
}


MVC/Views/Login/Index.cshtml
@model UserAccount.Models.Employee
<html>
<head>
    <style>
        Body {
            font-family: Calibri, Helvetica, sans-serif;
            background-color: pink;
        }

        button {
            background-color: #4CAF50;
            width: 100%;
            color: black;
            padding: 15px;
            margin: 10px 0px;
            border: none;
            cursor: pointer;
        }

        form {
            border: 3px solid #f1f1f1;
        }

        input[type=text], input[type=password] {
            width: 100%;
            margin: 8px 0;
            padding: 12px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button:hover {
            opacity: 0.7;
        }

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            margin: 10px 5px;
        }


        .container {
            padding: 25px;
            background-color: lightblue;
        }
    </style>
</head>
<body>
    <center> <h1> Employee Login </h1> </center>
    @using (Html.BeginForm("Authenticate", "Login", FormMethod.Post))
    {
        <label>Email : </label>
        @Html.TextBoxFor(m => m.Email)

        <label>Password : </label>
        @Html.TextBoxFor(m => m.Password)

        <input type="submit" value="Login" />
    }
     <button type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "NewAccount")'">Create New Account</button>
</body>
</html>  

MVC/Views/NewAccount/Index.cshtml
@model UserAccount.Models.Employee
<html>

<head>
    <style>
        Body {
            font-family: Calibri, Helvetica, sans-serif;
            background-color: pink;
        }

        button {
            background-color: #4CAF50;
            width: 100%;
            color: black;
            padding: 15px;
            margin: 10px 0px;
            border: none;
            cursor: pointer;
        }

        form {
            border: 3px solid #f1f1f1;
        }

        input[type=text], input[type=password] {
            width: 100%;
            margin: 8px 0;
            padding: 12px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button:hover {
            opacity: 0.7;
        }

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            margin: 10px 5px;
        }


        .container {
            padding: 25px;
            background-color: lightblue;
        }
    </style>
</head>
<body>
    <center> <h1> Create New Account </h1> </center>

    @using (Html.BeginForm("Create", "NewAccount", FormMethod.Post))
    {
        <label>Username : </label>
        @Html.TextBoxFor(m => m.UserName)

        <label>Email : </label>
        @Html.TextBoxFor(m => m.Email)

        <label>Phone : </label>
        @Html.TextBoxFor(m => m.Phone)

        <label>Address : </label>
        @Html.TextBoxFor(m => m.Address)

        <label>Password : </label>
        @Html.TextBoxFor(m => m.Password)

        <input class="cancelbtn"  type="submit" value="Submit" />
     
    }
    <button type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "Login")'">Cancel</button>

</body>
</html>

MVC/Views/UserData/Index.cshtml
@model UserAccount.Models.Employee
<html>
<head>
    <style>
        Body {
            font-family: Calibri, Helvetica, sans-serif;
            background-color: pink;
        }

        button {
            background-color: #4CAF50;
            width: 100%;
            color: black;
            padding: 15px;
            margin: 10px 0px;
            border: none;
            cursor: pointer;
        }

        form {
            border: 3px solid #f1f1f1;
        }

        input[type=text], input[type=password] {
            width: 100%;
            margin: 8px 0;
            padding: 12px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button:hover {
            opacity: 0.7;
        }

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            margin: 10px 5px;
        }


        .container {
            padding: 25px;
            background-color: lightblue;
        }
    </style>
</head>
<body>
    <center> <h1> Welcome @Model.UserName</h1> </center>

    @using (Html.BeginForm("Update", "UserData", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Id)

        <label>Email : </label>
        @Html.TextBoxFor(m => m.Email, new { @readonly = true })

        <label>Username : </label>
        @Html.TextBoxFor(m => m.UserName,Model.UserName)

        <label>Phone : </label>
        @Html.TextBoxFor(m => m.Phone,Model.Phone)

        <label>Address : </label>
        @Html.TextBoxFor(m => m.Address,Model.Address)

        <input type="submit" value="Update" />
    }
    <button type="button" value="Cancel" onclick="location.href='@Url.Action("Delete", "UserData",new {id=Model.Id})'">Delete My Record</button>

</body>
</html> 